### ISSUE TITLE
Relevant paper for Turing patterns?

### ISSUE THREAD

**Issue by juliohm** [JuliaEarth/TuringPatterns.jl#1]
Is there any paper that introduces this concept? I've never heard of it, but looks interesting.

**Comment by yurivish** [comment]
Hey, good question! I'll close this issue once I add some links to the readme. In the mean time, here's the main paper: http://www.jonathanmccabe.com/Cyclic_Symmetric_Multi-Scale_Turing_Patterns.pdf

That guy made these really cool pictures, but the description only goes up to relatively simple grayscale pictures -- above that, he keeps his method a secret.

https://www.flickr.com/photos/jonathanmccabe/albums/72157644907151060
https://www.flickr.com/photos/jonathanmccabe/sets/72157673446623356

**Comment by juliohm** [comment]
Thank you for sharing the papers @yurivish, I will close the issue.

**Comment by yurivish** [comment]
Thanks, but I actually think it’s a valid issue. :-)

The link to that paper should live in the reader somewhere, so I’ll close the issue when I’ve added it. This repository is a work in progress but it looks like I’m taking a little break.
