### ISSUE TITLE
Invitation to JuliaEarth

### ISSUE THREAD

**Issue by juliohm** [JuliaEarth/TuringPatterns.jl#10]
Dear @yurivish ,

I've created an organization to collect all related statistical work in Earth sciences. I would like to ask if you would be interested in being part of this organization? In the positive case, could we migrate the TuringPatterns.jl solver there? Thank you for your work, please let me know what you think. There is no problem if you prefer to keep the solver here :)

Best,
-Júlio

**Comment by yurivish** [comment]
Hi Júlio,

I think this package is of more general interest than the Earth sciences. I made it before knowing that it had any relevance there at all. So I think it’s good to keep it here, since it’s not specific to Earth sciences.

**Comment by juliohm** [comment]
No problem @yurivish :) I thought you would prefer that way. The name JuliaEarth is misleading, I couldn't find a better name for statistics in Earth sciences.
