### ISSUE TITLE
Migrate to GitHub Actions

### ISSUE THREAD

**Issue by juliohm** [JuliaEarth/TuringPatterns.jl#21]
Hi @yurivish , can we migrate from Travis CI to GitHub Actions?

I've done it for my other packages and can quickly do it here too. Most Julia packages are migrating due to recent changes in Travis CI with limited credit for open source projects.

**Comment by yurivish** [comment]
Sure. Anything I need to do?

**Comment by juliohm** [comment]
I can handle it, did for most of my packages already 👍🏽

**Comment by juliohm** [comment]
Fixed on master 👌🏽

**Comment by yurivish** [comment]
Great, thank you! :)
