### ISSUE TITLE
Maintenance and migration to JuliaEarth?

### ISSUE THREAD

**Issue by juliohm** [JuliaEarth/TuringPatterns.jl#22]
Hi @yurivish , hope you are doing well! I've noticed that some of the dependencies in this package are outdated, and are blocking updates downstream. I also know that you are not that much involved with Julia development anymore. I wonder if it would be ok to migrate this repository to JuliaEarth where I can maintain it more carefully over time. Would you be ok with that?

I could invite you to the organization and you would still have write access as before. Please let me know how we should proceed.

**Comment by yurivish** [comment]
Hi Júlio, yes, that would be fine by me – thanks for taking care of this package.

It looks like I need create permission on JuliaEarth to transfer it – feel free to do so yourself, or just let me know once I have the permission.

**Comment by juliohm** [comment]
Sent you the invitation to join the org. I think after that you should be able to transfer the repository. If it doesn't work please let me know and I will see what needs to be done.

**Comment by yurivish** [comment]
“ Moving repository to JuliaEarth/TuringPatterns.jl. This may take a few minutes.”
