### ISSUE TITLE
Can we get rid of Requires.jl?

### ISSUE THREAD

**Issue by juliohm** [JuliaEarth/TuringPatterns.jl#23]
Hi @yurivish , thanks for accepting the migration request. I would like to maintain the package more carefully moving forward and one thing that is difficult to track is the optional dependency with Requires.jl. Besides introducing load times, it is hard to see the effects of upstream changes when the package doesn't depend directly on the base packages we maintain. Would it be ok to get rid of Requires.jl and add Meshes.jl and GeoStatsBase.jl as dependencies or you still prefer to leave it that way? I understand if you prefer to preserve Requires.jl. Thanks again for helping and for this interesting algorithm.

**Comment by yurivish** [comment]
Your call. My instinct is to keep the package as low on dependencies as possible, particularly when the core functionality doesn’t inherently require them, but you have a better understanding of the maintenance story here. 

JuliaHub lists TuringPatterns as having zero dependents, so it doesn’t look like adding more dependents would transitively introduce load on downstream packages.

**Comment by juliohm** [comment]
Thank you @yurivish , I will see what is the best path forward, but it is a nice thing to depend on the Pkg manager with an actual formal dependency to control version and breaking changes. I was also considering a separate package where we could wrap some of the 3rd-party samplers, but that will demand even more time to maintain.

**Comment by yurivish** [comment]
Thanks!

**Comment by juliohm** [comment]
Fixed in the master branch 🙏🏽
