### ISSUE TITLE
Remove IO functions to reduce dependencies

### ISSUE THREAD

**Issue by juliohm** [JuliaEarth/TuringPatterns.jl#24]
Helper functions such as `saveframe` and friends are introducing Color types and FileIO as dependencies. But different people prefer to use different IO methods to store data on disk. In particular, it is very simple to cook these functions quickly in a script to save the Turing patterns with the desired format.

Now that we are introducing some breaking changes, it is a good opportunity to make the functionality more self-contained without IO.

**Comment by juliohm** [comment]
@yurivish can you please comment on the FixedPointNumbers dependency? How is it being used?

**Comment by yurivish** [comment]
I don't remember, but perhaps it's in order to use a `UInt8` as the underlying representation for each channel of a color type?

**Comment by juliohm** [comment]
Oh I see, I thought there was another reason, but it is probably related to the Images.jl ecosystem where fixed point numbers are the internal representation of some color types as you mentioned. Thanks for clarifying 👍🏽

**Comment by juliohm** [comment]
Closing as solved.
