### ISSUE TITLE
Consider shrinking the dependencies?

### ISSUE THREAD

**Issue by juliohm** [JuliaEarth/TuringPatterns.jl#4]
This package is awesome. I couldn't grasp the details of the algorithm in the references though, and I wonder if you have alternative papers that you could share?

Also, I wonder if you could eliminate some of the package dependencies like FileIO.jl and make this project more light? I would like to write a simulation solver for GeoStats.jl that generates Turing patterns by calling your implementation. :)

**Comment by yurivish** [comment]
Hi @juliohm,

I wouldn't mind making it slimmer but I'm a bit busy with other projects at the moment. I don't think it would be very difficult;  the heavy stuff all seems to be coming from https://github.com/yurivish/TuringPatterns.jl/blob/master/src/export.jl.

If I have some free time over the next few weeks I'll look into it! What's the strategy for dealing with that sort of "optional dependencies" these days?

Here's another blog post that I remember reading that goes into some detail about the concept and might help: https://softologyblog.wordpress.com/2011/07/05/multi-scale-turing-patterns/

**Comment by juliohm** [comment]
That would be great @yurivish, these patterns are quite intriguing! By the way, do you know if it is possible to simulate Turing patterns in which some of the pixels of the image have predefined values?

As an alternative to writing a separate package and calling your package under the hood, I could I also submit a PR to TuringPatterns.jl that adds a solver interface following the GeoStats.jl conventions.

The interface consists of adding a solver type as defined [here](https://github.com/juliohm/ImageQuilting.jl/blob/master/src/geostats_api.jl#L35-L47) and defining a single function as defined [here](https://github.com/juliohm/ImageQuilting.jl/blob/master/src/geostats_api.jl#L90-L105) called `solve_single` that would then call your `simulate` function and return the array with values.

I am quite happy with any of the two approaches: 1) shrinking TuringPatterns.jl so that it can be wrapped in a separate package, 2) making TuringPatterns.jl complaint with the GeoStats.jl API. Whatever fits your interests and goals. :+1:

**Comment by yurivish** [comment]
It seems that removing the include of `export.jl` would do the trick for the first option — does that sound right to you?

**Comment by juliohm** [comment]
Sounds good :+1: I can wrap the package in another package and define the solver.

P.S.: The blog post you shared is very helpful.

**Comment by juliohm** [comment]
Closing this issue given that we solved it already in #5
