### ISSUE TITLE
Build badge not updating

### ISSUE THREAD

**Issue by juliohm** [JuliaEarth/TuringPatterns.jl#8]
Hi @yurivish , the build badge is not updating. Are you sure you enabled Travis CI?

Thank you,
-Julio

**Comment by juliohm** [comment]
I am only asking because I would like to keep an eye on the build status in this table: https://github.com/juliohm/GeoStats.jl#simulation-problems

That way I can maintain the package as well :)

**Comment by yurivish** [comment]
Hey, I just added the monthly cron job -- apparently there was an "add" button I needed to press on that page. 

![image](https://user-images.githubusercontent.com/114388/54655237-9281ad80-4a97-11e9-9c2c-f12fe566fa0e.png)

We'll see if this takes.

**Comment by juliohm** [comment]
Thanks! I am seeing the badges now :) The coverage is a bit low, but that is another matter. I guess it is because there are source files in the repo that are not used. Closing the issue.
